name = "shellout"
version = "1.0.1-dev"
description = "A Gleam library for cross-platform shell operations"
licences = ["Apache-2.0"]

[repository]
repo = "shellout"
user = "tynanbe"
type = "github"

[[links]]
href = "https://gleam.run/"
title = "Website"

[dependencies]
gleam_erlang = "~> 0.17"
gleam_stdlib = "~> 0.26"

[dev-dependencies]
gleeunit = "~> 0.10"
