name = "shellout"
version = "1.3.0"
description = "A Gleam library for cross-platform shell operations"
licences = ["Apache-2.0"]

[repository]
repo = "shellout"
user = "tynanbe"
type = "github"

[[links]]
href = "https://gleam.run/"
title = "Website"

[dependencies]
gleam_erlang = "~> 0.9"
gleam_stdlib = "~> 0.29"

[dev-dependencies]
gleeunit = "~> 0.10"

[javascript.deno]
allow_env = true
allow_read = true
allow_run = true
